from dataclasses import dataclass
from typing import BinaryIO, Protocol


@dataclass(frozen=True)
class ObjectMetadata:
    key: str
    size: int
    content_type: str | None


class ObjectStorage(Protocol):
    def ensure_bucket(self) -> None: ...
    def put(self, key: str, data: BinaryIO, size: int, content_type: str) -> ObjectMetadata: ...
    def get(self, key: str) -> BinaryIO: ...
    def stat(self, key: str) -> ObjectMetadata: ...
    def delete(self, key: str) -> None: ...
    def presigned_get(self, key: str, expires_seconds: int = 900) -> str: ...
