FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libgl1 libxcb1 && \
    rm -rf /var/lib/apt/lists/*
COPY pyproject.toml .
COPY apps/api/app /app/app
COPY apps/api/assets /app/assets
COPY workers /app/workers
RUN pip install --no-cache-dir "."
COPY scripts /app/scripts
COPY alembic.ini /app/
COPY apps/api/alembic /app/apps/api/alembic
EXPOSE 8000
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
