FROM python:3.12-slim-bookworm@sha256:a116514e19457bcb7af7efe9c3dd0b9b71e85b317694e7882a1c52aa15a78134

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libglib2.0-0 \
        libgl1 \
        libxcb1 \
        libtesseract5=5.3.0-2 \
        tesseract-ocr=5.3.0-2 \
        tesseract-ocr-chi-sim=1:4.1.0-2 \
        tesseract-ocr-eng=1:4.1.0-2 \
        tesseract-ocr-osd=1:4.1.0-2 \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY apps/api/app /app/app
COPY apps/api/assets /app/assets
COPY workers /app/workers
RUN pip install --no-cache-dir "."
COPY scripts /app/scripts
COPY alembic.ini /app/
COPY apps/api/alembic /app/apps/api/alembic
EXPOSE 8000
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]
